// MIDI Controller defaults map (from MIDI.midnam spec)
// Maps controller numbers to their standard names and descriptions

export const MIDI_CONTROLLER_DEFAULTS = {
    0: "Bank Select",
    1: "Modulation Wheel or Lever",
    2: "Breath Controller",
    3: "Undefined",
    4: "Foot Controller",
    5: "Portamento Time",
    6: "Data Entry MSB",
    7: "Channel Volume",
    8: "Balance",
    9: "Undefined",
    10: "Pan",
    11: "Expression Controller",
    12: "Effect Control 1",
    13: "Effect Control 2",
    14: "Undefined",
    15: "Undefined",
    16: "General Purpose Controller 1",
    17: "General Purpose Controller 2",
    18: "General Purpose Controller 3",
    19: "General Purpose Controller 4",
    20: "Undefined",
    21: "Undefined",
    22: "Undefined",
    23: "Undefined",
    24: "Undefined",
    25: "Undefined",
    26: "Undefined",
    27: "Undefined",
    28: "Undefined",
    29: "Undefined",
    30: "Undefined",
    31: "Undefined",
    32: "LSB for Control 0 (Bank Select) (Fine)",
    33: "LSB for Control 1 (Modulation Wheel or Lever) (Fine)",
    34: "LSB for Control 2 (Breath Controller) (Fine)",
    35: "LSB for Control 3 (Undefined) (Fine)",
    36: "LSB for Control 4 (Foot Controller) (Fine)",
    37: "LSB for Control 5 (Portamento Time) (Fine)",
    38: "LSB for Control 6 (Data Entry) (Fine)",
    39: "LSB for Control 7 (Channel Volume) (Fine)",
    40: "LSB for Control 8 (Balance) (Fine)",
    41: "LSB for Control 9 (Undefined) (Fine)",
    42: "LSB for Control 10 (Pan) (Fine)",
    43: "LSB for Control 11 (Expression Controller) (Fine)",
    44: "LSB for Control 12 (Effect control 1) (Fine)",
    45: "LSB for Control 13 (Effect control 2) (Fine)",
    46: "LSB for Control 14 (Undefined) (Fine)",
    47: "LSB for Control 15 (Undefined) (Fine)",
    48: "LSB for Control 16 (General Purpose Controller 1) (Fine)",
    49: "LSB for Control 17 (General Purpose Controller 2) (Fine)",
    50: "LSB for Control 18 (General Purpose Controller 3) (Fine)",
    51: "LSB for Control 19 (General Purpose Controller 4) (Fine)",
    52: "LSB for Control 20 (Undefined) (Fine)",
    53: "LSB for Control 21 (Undefined) (Fine)",
    54: "LSB for Control 22 (Undefined) (Fine)",
    55: "LSB for Control 23 (Undefined) (Fine)",
    56: "LSB for Control 24 (Undefined) (Fine)",
    57: "LSB for Control 25 (Undefined) (Fine)",
    58: "LSB for Control 26 (Undefined) (Fine)",
    59: "LSB for Control 27 (Undefined) (Fine)",
    60: "LSB for Control 28 (Undefined) (Fine)",
    61: "LSB for Control 29 (Undefined) (Fine)",
    62: "LSB for Control 30 (Undefined) (Fine)",
    63: "LSB for Control 31 (Undefined) (Fine)",
    64: "Damper Pedal on/off (Sustain) ≤63 off, ≥64 on",
    65: "Portamento On/Off ≤63 off, ≥64 on",
    66: "Sostenuto On/Off ≤63 off, ≥64 on",
    67: "Soft Pedal On/Off ≤63 off, ≥64 on",
    68: "Legato Footswitch ≤63 Normal, ≥64 Legato",
    69: "Hold 2 ≤63 off, ≥64 on",
    70: "Sound Controller 1 (default: Sound Variation) (Fine)",
    71: "Sound Controller 2 (default: Timbre/Harmonic Intens.) (Fine)",
    72: "Sound Controller 3 (default: Release Time) (Fine)",
    73: "Sound Controller 4 (default: Attack Time) (Fine)",
    74: "Sound Controller 5 (default: Brightness) (Fine)",
    75: "Sound Controller 6 (default: Decay Time) (Fine)",
    76: "Sound Controller 7 (default: Vibrato Rate) (Fine)",
    77: "Sound Controller 8 (default: Vibrato Depth) (Fine)",
    78: "Sound Controller 9 (default: Vibrato Delay) (Fine)",
    79: "Sound Controller 10 (default undefined) (Fine)",
    80: "General Purpose Controller 5 (Fine)",
    81: "General Purpose Controller 6 (Fine)",
    82: "General Purpose Controller 7 (Fine)",
    83: "General Purpose Controller 8 (Fine)",
    84: "Portamento Control (Fine)",
    85: "(Undefined)",
    86: "(Undefined)",
    87: "(Undefined)",
    88: "High Resolution Velocity Prefix (Velocity LSB)",
    89: "(Undefined)",
    90: "(Undefined)",
    91: "Effects 1 Depth (default: Reverb Send Level)",
    92: "Effects 2 Depth",
    93: "Effects 3 Depth (default: Chorus Send Level)",
    94: "Effects 4 Depth",
    95: "Effects 5 Depth",
    96: "Data Increment (Data Entry +1)",
    97: "Data Decrement (Data Entry -1)",
    98: "Non-Registered Parameter Number LSB",
    99: "Non-Registered Parameter Number MSB",
    100: "Registered Parameter Number LSB",
    101: "Registered Parameter Number MSB",
    102: "(Undefined)",
    103: "(Undefined)",
    104: "(Undefined)",
    105: "(Undefined)",
    106: "(Undefined)",
    107: "(Undefined)",
    108: "(Undefined)",
    109: "(Undefined)",
    110: "(Undefined)",
    111: "(Undefined)",
    112: "(Undefined)",
    113: "(Undefined)",
    114: "(Undefined)",
    115: "(Undefined)",
    116: "(Undefined)",
    117: "(Undefined)",
    118: "(Undefined)",
    119: "(Undefined)",
    120: "[Channel Mode Message] All Sound Off",
    121: "[Channel Mode Message] Reset All Controllers",
    122: "[Channel Mode Message] Local Control On/Off 0 off, 127 on",
    123: "[Channel Mode Message] All Notes Off",
    124: "[Channel Mode Message] Omni Mode Off (+ all notes off)",
    125: "[Channel Mode Message] Omni Mode On (+ all notes off)",
    126: "[Channel Mode Message] Mono Mode On (+ poly off, + all notes off)",
    127: "[Channel Mode Message] Poly Mode On (+ mono off, +all notes off) 0"
};

/**
 * Get the default name for a MIDI controller number
 * @param {number} controllerNumber - Controller number (0-127)
 * @returns {string} Default name or 'Unknown'
 */
export function getMIDIControllerName(controllerNumber) {
    return MIDI_CONTROLLER_DEFAULTS[controllerNumber] || 'Unknown';
}

